-- Execute this SQL query in your Supabase SQL Editor (https://supabase.com/dashboard/project/ybumgwhcbuovrjugdkas/sql)

-- 1. Table for boyfriend admin remote messages
CREATE TABLE IF NOT EXISTS public.admin_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  sent_by TEXT DEFAULT 'Hirthik',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table for girlfriend live hydration stats
CREATE TABLE IF NOT EXISTS public.hydration_stats (
  id TEXT PRIMARY KEY DEFAULT 'current_stats',
  girlfriend_name TEXT DEFAULT 'Malar',
  boyfriend_name TEXT DEFAULT 'Hirthik',
  daily_goal INT DEFAULT 2500,
  today_total INT DEFAULT 0,
  today_percentage INT DEFAULT 0,
  entries_count INT DEFAULT 0,
  last_sip_timestamp TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & allow anonymous public read/write for HydraLove app
ALTER TABLE public.admin_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hydration_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read admin_messages" ON public.admin_messages FOR SELECT USING (true);
CREATE POLICY "Allow public insert admin_messages" ON public.admin_messages FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read hydration_stats" ON public.hydration_stats FOR SELECT USING (true);
CREATE POLICY "Allow public insert hydration_stats" ON public.hydration_stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update hydration_stats" ON public.hydration_stats FOR UPDATE USING (true);
